//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Consumo.WCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.IBD")]
    public interface IBD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/CrearDTParametros", ReplyAction="http://tempuri.org/IBD/CrearDTParametrosResponse")]
        System.Data.DataTable CrearDTParametros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/CrearDTParametros", ReplyAction="http://tempuri.org/IBD/CrearDTParametrosResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> CrearDTParametrosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/ListarDatos", ReplyAction="http://tempuri.org/IBD/ListarDatosResponse")]
        Web_Consumo.WCF.ListarDatosResponse ListarDatos(Web_Consumo.WCF.ListarDatosRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/ListarDatos", ReplyAction="http://tempuri.org/IBD/ListarDatosResponse")]
        System.Threading.Tasks.Task<Web_Consumo.WCF.ListarDatosResponse> ListarDatosAsync(Web_Consumo.WCF.ListarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/Ins_Mod_Del_Datos", ReplyAction="http://tempuri.org/IBD/Ins_Mod_Del_DatosResponse")]
        Web_Consumo.WCF.Ins_Mod_Del_DatosResponse Ins_Mod_Del_Datos(Web_Consumo.WCF.Ins_Mod_Del_DatosRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/Ins_Mod_Del_Datos", ReplyAction="http://tempuri.org/IBD/Ins_Mod_Del_DatosResponse")]
        System.Threading.Tasks.Task<Web_Consumo.WCF.Ins_Mod_Del_DatosResponse> Ins_Mod_Del_DatosAsync(Web_Consumo.WCF.Ins_Mod_Del_DatosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarDatos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public ListarDatosRequest() {
        }
        
        public ListarDatosRequest(string sNombreSP, string sMsjError) {
            this.sNombreSP = sNombreSP;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarDatosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable ListarDatosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public ListarDatosResponse() {
        }
        
        public ListarDatosResponse(System.Data.DataTable ListarDatosResult, string sMsjError) {
            this.ListarDatosResult = ListarDatosResult;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ins_Mod_Del_Datos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Ins_Mod_Del_DatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool bBandera;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Data.DataTable DT_Parametros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sMsjError;
        
        public Ins_Mod_Del_DatosRequest() {
        }
        
        public Ins_Mod_Del_DatosRequest(string sNombreSP, bool bBandera, System.Data.DataTable DT_Parametros, string sMsjError) {
            this.sNombreSP = sNombreSP;
            this.bBandera = bBandera;
            this.DT_Parametros = DT_Parametros;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ins_Mod_Del_DatosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Ins_Mod_Del_DatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Ins_Mod_Del_DatosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public Ins_Mod_Del_DatosResponse() {
        }
        
        public Ins_Mod_Del_DatosResponse(string Ins_Mod_Del_DatosResult, string sMsjError) {
            this.Ins_Mod_Del_DatosResult = Ins_Mod_Del_DatosResult;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBDChannel : Web_Consumo.WCF.IBD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BDClient : System.ServiceModel.ClientBase<Web_Consumo.WCF.IBD>, Web_Consumo.WCF.IBD {
        
        public BDClient() {
        }
        
        public BDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable CrearDTParametros() {
            return base.Channel.CrearDTParametros();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> CrearDTParametrosAsync() {
            return base.Channel.CrearDTParametrosAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Consumo.WCF.ListarDatosResponse Web_Consumo.WCF.IBD.ListarDatos(Web_Consumo.WCF.ListarDatosRequest request) {
            return base.Channel.ListarDatos(request);
        }
        
        public System.Data.DataTable ListarDatos(string sNombreSP, ref string sMsjError) {
            Web_Consumo.WCF.ListarDatosRequest inValue = new Web_Consumo.WCF.ListarDatosRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.sMsjError = sMsjError;
            Web_Consumo.WCF.ListarDatosResponse retVal = ((Web_Consumo.WCF.IBD)(this)).ListarDatos(inValue);
            sMsjError = retVal.sMsjError;
            return retVal.ListarDatosResult;
        }
        
        public System.Threading.Tasks.Task<Web_Consumo.WCF.ListarDatosResponse> ListarDatosAsync(Web_Consumo.WCF.ListarDatosRequest request) {
            return base.Channel.ListarDatosAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Consumo.WCF.Ins_Mod_Del_DatosResponse Web_Consumo.WCF.IBD.Ins_Mod_Del_Datos(Web_Consumo.WCF.Ins_Mod_Del_DatosRequest request) {
            return base.Channel.Ins_Mod_Del_Datos(request);
        }
        
        public string Ins_Mod_Del_Datos(string sNombreSP, bool bBandera, System.Data.DataTable DT_Parametros, ref string sMsjError) {
            Web_Consumo.WCF.Ins_Mod_Del_DatosRequest inValue = new Web_Consumo.WCF.Ins_Mod_Del_DatosRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.bBandera = bBandera;
            inValue.DT_Parametros = DT_Parametros;
            inValue.sMsjError = sMsjError;
            Web_Consumo.WCF.Ins_Mod_Del_DatosResponse retVal = ((Web_Consumo.WCF.IBD)(this)).Ins_Mod_Del_Datos(inValue);
            sMsjError = retVal.sMsjError;
            return retVal.Ins_Mod_Del_DatosResult;
        }
        
        public System.Threading.Tasks.Task<Web_Consumo.WCF.Ins_Mod_Del_DatosResponse> Ins_Mod_Del_DatosAsync(Web_Consumo.WCF.Ins_Mod_Del_DatosRequest request) {
            return base.Channel.Ins_Mod_Del_DatosAsync(request);
        }
    }
}
