//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BLL.WCF_Aerolinea_BD {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IBD", Namespace="http://tempuri.org/")]
    public partial class BD : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CrearDTParametrosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarDatosOperationCompleted;
        
        private System.Threading.SendOrPostCallback Ins_Mod_Del_DatosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BD() {
            this.Url = global::BLL.Properties.Settings.Default.BLL_com_mcotosvr_servicios_aerolineas_BD;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CrearDTParametrosCompletedEventHandler CrearDTParametrosCompleted;
        
        /// <remarks/>
        public event ListarDatosCompletedEventHandler ListarDatosCompleted;
        
        /// <remarks/>
        public event Ins_Mod_Del_DatosCompletedEventHandler Ins_Mod_Del_DatosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBD/CrearDTParametros", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable CrearDTParametros() {
            object[] results = this.Invoke("CrearDTParametros", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void CrearDTParametrosAsync() {
            this.CrearDTParametrosAsync(null);
        }
        
        /// <remarks/>
        public void CrearDTParametrosAsync(object userState) {
            if ((this.CrearDTParametrosOperationCompleted == null)) {
                this.CrearDTParametrosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearDTParametrosOperationCompleted);
            }
            this.InvokeAsync("CrearDTParametros", new object[0], this.CrearDTParametrosOperationCompleted, userState);
        }
        
        private void OnCrearDTParametrosOperationCompleted(object arg) {
            if ((this.CrearDTParametrosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearDTParametrosCompleted(this, new CrearDTParametrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBD/ListarDatos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable ListarDatos([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sNombreSP, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string sMsjError) {
            object[] results = this.Invoke("ListarDatos", new object[] {
                        sNombreSP,
                        sMsjError});
            sMsjError = ((string)(results[1]));
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ListarDatosAsync(string sNombreSP, string sMsjError) {
            this.ListarDatosAsync(sNombreSP, sMsjError, null);
        }
        
        /// <remarks/>
        public void ListarDatosAsync(string sNombreSP, string sMsjError, object userState) {
            if ((this.ListarDatosOperationCompleted == null)) {
                this.ListarDatosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarDatosOperationCompleted);
            }
            this.InvokeAsync("ListarDatos", new object[] {
                        sNombreSP,
                        sMsjError}, this.ListarDatosOperationCompleted, userState);
        }
        
        private void OnListarDatosOperationCompleted(object arg) {
            if ((this.ListarDatosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarDatosCompleted(this, new ListarDatosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBD/Ins_Mod_Del_Datos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Ins_Mod_Del_Datos([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sNombreSP, bool bBandera, [System.Xml.Serialization.XmlIgnoreAttribute()] bool bBanderaSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Data.DataTable DT_Parametros, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string sMsjError) {
            object[] results = this.Invoke("Ins_Mod_Del_Datos", new object[] {
                        sNombreSP,
                        bBandera,
                        bBanderaSpecified,
                        DT_Parametros,
                        sMsjError});
            sMsjError = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Ins_Mod_Del_DatosAsync(string sNombreSP, bool bBandera, bool bBanderaSpecified, System.Data.DataTable DT_Parametros, string sMsjError) {
            this.Ins_Mod_Del_DatosAsync(sNombreSP, bBandera, bBanderaSpecified, DT_Parametros, sMsjError, null);
        }
        
        /// <remarks/>
        public void Ins_Mod_Del_DatosAsync(string sNombreSP, bool bBandera, bool bBanderaSpecified, System.Data.DataTable DT_Parametros, string sMsjError, object userState) {
            if ((this.Ins_Mod_Del_DatosOperationCompleted == null)) {
                this.Ins_Mod_Del_DatosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIns_Mod_Del_DatosOperationCompleted);
            }
            this.InvokeAsync("Ins_Mod_Del_Datos", new object[] {
                        sNombreSP,
                        bBandera,
                        bBanderaSpecified,
                        DT_Parametros,
                        sMsjError}, this.Ins_Mod_Del_DatosOperationCompleted, userState);
        }
        
        private void OnIns_Mod_Del_DatosOperationCompleted(object arg) {
            if ((this.Ins_Mod_Del_DatosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Ins_Mod_Del_DatosCompleted(this, new Ins_Mod_Del_DatosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void CrearDTParametrosCompletedEventHandler(object sender, CrearDTParametrosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearDTParametrosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearDTParametrosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ListarDatosCompletedEventHandler(object sender, ListarDatosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarDatosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarDatosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string sMsjError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Ins_Mod_Del_DatosCompletedEventHandler(object sender, Ins_Mod_Del_DatosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Ins_Mod_Del_DatosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Ins_Mod_Del_DatosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string sMsjError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591